### ISSUE TITLE
Workers dynamically join & leave 

### ISSUE THREAD

**Issue by immars** [dmlc/parameter_server#17]
Hi,

In data parallelism, it is reasonable(or is it? ) to allow workers start to train a model replica at anytime, for 2 reasons: a) worker's resource may not all available at the start of training, b) for better convergence, 1 worker could start first to train a while to give a kickstart before other workers join the group ( mentioned here: http://research.google.com/archive/large_deep_networks_nips2012.html ).

Currently it seems that all servers/workers should be initiated before anyone of them start to run. And it seems to be controlled by PostOffice and can not easily be customized with my Scheduler or Server. 

Thanks,

**Comment by mli** [comment]
Hi Lisen,

Please have a check at the dev branch, that feature is partially supported.
But I need more tests.

Best
Mu

**Comment by immars** [comment]
Thanks again @mli !
