### ISSUE TITLE
Missing .h file after "make clean"

### ISSUE THREAD

**Issue by sunghlin** [dmlc/parameter_server#19]
Hi

For the first time compilation, everything works well. However, after I typed "make clean" and make again, it keeps telling me "wire_format.h:44:43: fatal error: google/protobuf/descriptor.pb.h: No such file or directory". 

Does "find . -name "*.pb.[ch]*" -delete" really need to be in the command?

Thanks,

**Comment by mli** [comment]
changed from find . to find src :)
