### ISSUE TITLE
max_delay in async_sgd

### ISSUE THREAD

**Issue by sunghlin** [dmlc/parameter_server#20]
Hi

Can we change the consistency condition in async_sgd model? I see you defined the max_delay, but never use it.

Thanks,

**Comment by mli** [comment]
the current version didn't implemented the bounded delay consistency for asynchronous sgd. i tested the bounded version, but didn't see any benefits if using a very large dataset, and it makes the semantic a little strange. 

the batch algorithm, darlin, has the bounded delay implementation
